options:
logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - image-upload
  - --source=.
  - --runtime=python310
  - --trigger-http
  - --allow-unauthenticated
