name: Deploy Cloud Function

on:
  push:
    branches:
      - blue-background
      - green-background

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy Cloud Function
        run: gcloud functions deploy my-cloud-function --region us-central1
