name: Deploy to Google Cloud Function

on:
  push:
    branches:
      - blue-background
      - green-background

env:
  GCP_PROJECT_ID: ${{ env.GCP_PROJECT_ID }}
  FUNCTION_NAME: upload-image

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy to GCP Cloud Function
      run: |
        gcloud functions deploy ${{ env.FUNCTION_NAME }} \
          --entry-point upload-image \
          --runtime python310 \
          --trigger-http \
          --allow-unauthenticated
