name: Deploy to GCP

on:
  push:
    branches:
      - blue-background
      - green-background

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy to App Engine
      run: |
        gcloud app deploy app.yaml --project ${{ secrets.GCP_PROJECT_ID }}
